(define-module (examples restaurant detail inventory)
  #:use-module (srfi srfi-1)
  #:use-module (ice-9 hash-table)
  #:use-module (cpnet core)
  #:use-module (cpnet system)
  #:use-module (cpnet detail)
  #:export (make-inventory-component))

(define (_make-stock-updater prop-id inventory-dirty-flag)
  (lambda (ingredient-name event-cell stock-cell)
    (make-propagator
     (prop-id (format #f "update-~a-stock" ingredient-name))
     event-cell stock-cell
     (lambda (amount src-cell)
       (if (and amount (number? amount))
           (let ((new-stock (- (cell-value stock-cell) amount)))
             (cons new-stock (list (make-effect 'set-value (cons src-cell #f))
                                   (make-effect 'set-value (cons inventory-dirty-flag #t)))))
           (if amount
               (cons #f (list (make-effect 'set-value (cons src-cell #f))))
               (cons #f '())))))))

(define (define-inventory-propagators cells prop-id)
  (let* ((public-ingredients-decrement (hash-ref cells 'public-ingredients-decrement))
         (inventory-dirty-flag (hash-ref cells 'inventory-dirty-flag))
         (out-low-stock-trigger (hash-ref cells 'out-low-stock-trigger))
         (cell-event-cell-map (hash-ref cells 'event-cell-map))
         (cell-all-stock-info (hash-ref cells 'all-stock-info))
         (event-pasta (hash-ref cells 'event-pasta)) (stock-pasta (hash-ref cells 'stock-pasta))
         (event-sauce (hash-ref cells 'event-sauce)) (stock-sauce (hash-ref cells 'stock-sauce))
         (event-lettuce (hash-ref cells 'event-lettuce)) (stock-lettuce (hash-ref cells 'stock-lettuce))
         (event-tomato (hash-ref cells 'event-tomato)) (stock-tomato (hash-ref cells 'stock-tomato))
         (event-dough (hash-ref cells 'event-dough)) (stock-dough (hash-ref cells 'stock-dough))
         (event-cheese (hash-ref cells 'event-cheese)) (stock-cheese (hash-ref cells 'stock-cheese))
         (p-dispatch-ingredients
          (make-propagator (prop-id "dispatch-ingredients") public-ingredients-decrement public-ingredients-decrement
            (lambda (ingredients-list src-cell)
              (if (and ingredients-list (not (null? ingredients-list)))
                  (let* ((aggregated (make-hash-table))
                         (effects '()))
                    (for-each
                     (lambda (item)
                       (let ((name (car item)) (amount (cadr item)))
                         (hash-set! aggregated name (+ amount (hash-ref aggregated name 0)))))
                     ingredients-list)
                    (let ((current-event-map (cell-value cell-event-cell-map)))
                      (hash-for-each
                       (lambda (name amount)
                         (let ((event-cell (cdr (assoc name current-event-map))))
                           (when event-cell
                             (set! effects (cons (make-effect 'set-value (cons event-cell amount))
                                                 effects)))))
                       aggregated))
                    (cons #f (append effects (list (make-effect 'set-value (cons src-cell #f))))))
                  (cons #f '())))))
         (make-stock-updater (_make-stock-updater prop-id inventory-dirty-flag))
         (p-check-all-stock-levels
          (make-propagator (prop-id "check-all-stock-levels")
                           inventory-dirty-flag out-low-stock-trigger
            (lambda (is-dirty src-cell)
              (if is-dirty
                  (let* ((current-stock-info (cell-value cell-all-stock-info))
                         (items-and-effects
                          (filter-map
                           (lambda (info)
                             (let ((name (list-ref info 0)) (stock-cell (list-ref info 1))
                                   (threshold (list-ref info 2)) (alert-cell (list-ref info 3)))
                               (if (and (<= (cell-value stock-cell) threshold) (not (cell-value alert-cell)))
                                   (list (list name (cell-value stock-cell))
                                         (make-effect 'set-value (cons alert-cell #t)))
                                   #f)))
                           current-stock-info))
                         (low-stock-items (map car items-and-effects))
                         (set-alert-effects (map cadr items-and-effects)))
                    (cons (if (null? low-stock-items) #f low-stock-items)
                          (append set-alert-effects (list (make-effect 'set-value (cons src-cell #f))))))
                  (cons #f '()))))))
    (list p-dispatch-ingredients
          p-check-all-stock-levels
          (make-stock-updater 'pasta event-pasta stock-pasta)
          (make-stock-updater 'sauce event-sauce stock-sauce)
          (make-stock-updater 'lettuce event-lettuce stock-lettuce)
          (make-stock-updater 'tomato event-tomato stock-tomato)
          (make-stock-updater 'dough event-dough stock-dough)
          (make-stock-updater 'cheese event-cheese stock-cheese))))

(define make-inventory-component
  (make-component-factory
   '((public-ingredients-decrement #f)
     (out-low-stock-trigger #f)
     (stock-pasta 100) (stock-sauce 100) (stock-lettuce 50)
     (stock-tomato 50) (stock-dough 50) (stock-cheese 50))
   '((event-pasta #f) (event-sauce #f) (event-lettuce #f)
     (event-tomato #f) (event-dough #f) (event-cheese #f)
     (alert-sent-pasta #f) (alert-sent-sauce #f) (alert-sent-lettuce #f)
     (alert-sent-tomato #f) (alert-sent-dough #f) (alert-sent-cheese #f)
     (inventory-dirty-flag #f)
     (event-cell-map 'placeholder)
     (all-stock-info 'placeholder))
   (lambda (cells prop-id)
     (let ((stock-pasta (hash-ref cells 'stock-pasta)) (alert-sent-pasta (hash-ref cells 'alert-sent-pasta))
           (stock-sauce (hash-ref cells 'stock-sauce)) (alert-sent-sauce (hash-ref cells 'alert-sent-sauce))
           (stock-lettuce (hash-ref cells 'stock-lettuce)) (alert-sent-lettuce (hash-ref cells 'alert-sent-lettuce))
           (stock-tomato (hash-ref cells 'stock-tomato)) (alert-sent-tomato (hash-ref cells 'alert-sent-tomato))
           (stock-dough (hash-ref cells 'stock-dough)) (alert-sent-dough (hash-ref cells 'alert-sent-dough))
           (stock-cheese (hash-ref cells 'stock-cheese)) (alert-sent-cheese (hash-ref cells 'alert-sent-cheese))
           (event-pasta (hash-ref cells 'event-pasta)) (event-sauce (hash-ref cells 'event-sauce))
           (event-lettuce (hash-ref cells 'event-lettuce)) (event-tomato (hash-ref cells 'event-tomato))
           (event-dough (hash-ref cells 'event-dough)) (event-cheese (hash-ref cells 'event-cheese)))
       (cell-set-value! (hash-ref cells 'event-cell-map)
                        `((pasta . ,event-pasta) (sauce . ,event-sauce)
                          (lettuce . ,event-lettuce) (tomato . ,event-tomato)
                          (dough . ,event-dough) (cheese . ,event-cheese)))
       (cell-set-value! (hash-ref cells 'all-stock-info)
                        (list (list 'pasta stock-pasta 10 alert-sent-pasta)
                              (list 'sauce stock-sauce 10 alert-sent-sauce)
                              (list 'lettuce stock-lettuce 10 alert-sent-lettuce)
                              (list 'tomato stock-tomato 10 alert-sent-tomato)
                              (list 'dough stock-dough 10 alert-sent-dough)
                              (list 'cheese stock-cheese 10 alert-sent-cheese))))
     (define-inventory-propagators cells prop-id))))
