(use-modules (cpnet core)
             (cpnet runtime)
             (examples restaurant dynamic-architecture))

(display "--- Restaurant Simulation (Multi-file Architecture) ---\n")

(display "\n--- Simulation ---\n")
(define (sell-dish dish-symbol quantity)
  (format #t "\n--- Selling ~a of ~a ---\n" quantity dish-symbol)
  (let ((event `((item . ,dish-symbol) (quantity . ,quantity))))
    (cell-set-value! sale-event (list event)))
  (runtime-settle! TheRestaurantSystem)
  (runtime-show-state TheRestaurantSystem "State after sale"))

(define (add-recipe name ingredients)
  (format #t "\n--- Adding recipe for ~a ---\n" name)
  (cell-set-value! new-recipe-event (cons name ingredients))
  (runtime-settle! TheRestaurantSystem))

(runtime-show-state TheRestaurantSystem "Initial State")

(sell-dish 'spaghetti 1)
(sell-dish 'salad 2)

(add-recipe 'pizza '((dough 1) (cheese 1) (sauce 1)))
(sell-dish 'pizza 1)

(display "\n--- Selling 40 salads silently to lower stock...\n")
(let ((batch-sale-events (make-list 40 '((item . salad) (quantity . 1)))))
  (cell-set-value! sale-event batch-sale-events)
  (runtime-settle! TheRestaurantSystem))
(runtime-show-state TheRestaurantSystem "State after selling 40 salads")

(display "\n--- Selling one more salad to trigger the alert ---\n")
(sell-dish 'salad 1)

(display "\nFinal Check:\n")
(let ((final-pasta (cell-value (hash-ref inventory-cells 'stock-pasta)))
      (final-sauce (cell-value (hash-ref inventory-cells 'stock-sauce)))
      (final-lettuce (cell-value (hash-ref inventory-cells 'stock-lettuce)))
      (final-tomato (cell-value (hash-ref inventory-cells 'stock-tomato)))
      (final-dough (cell-value (hash-ref inventory-cells 'stock-dough)))
      (final-cheese (cell-value (hash-ref inventory-cells 'stock-cheese))))
  (format #t "Final pasta stock: ~a (Expected: 99)\n" final-pasta)
  (format #t "Final sauce stock: ~a (Expected: 98)\n" final-sauce)
  (format #t "Final lettuce stock: ~a (Expected: 7)\n" final-lettuce)
  (format #t "Final tomato stock: ~a (Expected: 7)\n" final-tomato)
  (format #t "Final dough stock: ~a (Expected: 49)\n" final-dough)
  (format #t "Final cheese stock: ~a (Expected: 49)\n" final-cheese)
  (if (and (= final-pasta 99) (= final-sauce 98)
           (= final-lettuce 7) (= final-tomato 7)
           (= final-dough 49) (= final-cheese 49))
      (display "Success\n")))
