(define-module (cpnet runtime)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-11)
  #:use-module (ice-9 hash-table)
  #:use-module ((cpnet core) :prefix core:)
  #:use-module ((cpnet category) :prefix cat:)
  #:use-module (cpnet dsl)
  #:use-module (cpnet system)
  #:export (
	    runtime-settle!
	    runtime-step!
	    runtime-execute-effects
	    runtime-show-state))

(define (get-net system-or-net)
  (if (system? system-or-net)
      (system-get-net system-or-net)
      system-or-net))

(define (runtime-execute-effects effects system)
  (let ((changed? #f)
        (activated-cells '()))
    (for-each
     (lambda (effect)
       (case (core:effect-type effect)
         ((display) (display (core:effect-payload effect)))
         ((set-value)
          (let* ((payload (core:effect-payload effect))
                 (cell (car payload))
                 (new-val (cdr payload)))
            (when (not (equal? (core:cell-value cell) new-val))
              (core:cell-set-value! cell new-val)
              (set! changed? #t)
              (set! activated-cells (cons cell activated-cells)))))
         ((set-cell)
           (let* ((payload (core:effect-payload effect))
                  (cell (car payload))
                  (new-val (cadr payload)))
             (when (not (equal? (core:cell-value cell) new-val))
               (core:cell-set-value! cell new-val)
               (set! changed? #t)
               (set! activated-cells (cons cell activated-cells)))))
         ((remove-subsystem)
          (let* ((payload (core:effect-payload effect))
                 (sys (if system system (current-system))))
            (system-remove-subsystem! sys payload)
            (set! changed? #t)))
         ((add-subsystem)
          (let* ((payload (core:effect-payload effect))
                 (name (car payload))
                 (cat-proc (cadr payload))
                 (sys (if system system (current-system)))
                 (sub-sys (cat-proc name)))
            (add-subsystem! sys sub-sys)
            (set! changed? #t)))
         ((add-morphisms)
           (let* ((payload (core:effect-payload effect))
                  (sys (if system system (current-system)))
                  (resolve-ref (lambda (ref)
                                 (if (core:cell? ref) ref
                                     (let ((cat-name (car ref))
                                           (cell-name (cadr ref)))
                                       (or (system-find-cell sys cat-name cell-name)
                                           (error "add-morphisms effect: could not resolve cell ref" ref))))))
                  (new-mors (map (lambda (desc)
                                   (let* ((src-refs (car desc))
                                          (tgt-refs (cadr desc))
                                          (fn (caddr desc))
                                          (src (core:map-maybe resolve-ref src-refs))
                                          (tgt (core:map-maybe resolve-ref tgt-refs)))
                                     (core:make-propagator (gensym "dyn-wire-") src tgt fn)))
                                 payload)))
             (system-add-morphisms sys new-mors)
             (for-each
              (lambda (mor)
                (let ((dom (cat:arrow-dom mor)))
                  (if (list? dom)
                      (set! activated-cells (append dom activated-cells))
                      (when dom (set! activated-cells (cons dom activated-cells))))))
              new-mors)
             (set! changed? #t)))
         (else (format #t "Unknown effect: ~a\n" (core:effect-type effect)))))
     effects)
    (values changed? (delete-duplicates activated-cells))))

(define (runtime-show-state system-or-net title)
  (display (format #f "\n--- [~a] cpnet state ---\n" title))
  (let ((C (get-net system-or-net)))
    (for-each
     (lambda (c)
       (display (format #f "Cell ~a: ~a\n"
                        (core:cell-id c)
                        (core:cell-value c))))
     (sort (cat:category-objects C)
           (lambda (a b)
             (string<?
              (symbol->string (core:cell-id a))
              (symbol->string (core:cell-id b)))))))
  (display "--------------------------------\n"))

(define (_runtime-collect-updates C active-cells)
  (let ((effects '())
        (potential-updates (make-hash-table))
        (executed-mors '()))
    (let* ((all-mors (cat:category-morphisms C))
           (compute-mors (filter (lambda (m)
                                   (let* ((id-sym (cat:arrow-id m))
                                          (id-str (symbol->string id-sym)))
                                     (not (string-contains id-str "id-"))))
                                 all-mors))
           (relevant-mors (if (not active-cells)
                              compute-mors
                              (filter (lambda (m)
                                        (let ((dom (cat:arrow-dom m)))
                                          (if (list? dom)
                                              (any (lambda (d) (member d active-cells eq?)) dom)
                                              (member dom active-cells))))
                                      compute-mors)))
           (sorted-mors (sort relevant-mors
                              (lambda (a b) (> (cat:arrow-priority a)
                                               (cat:arrow-priority b))))))
      (for-each
       (lambda (m)
         (let* ((srcs (cat:arrow-dom m))
                (tgts (cat:arrow-cod m)))
           ;; Source가 유효한지 확인. (리스트인 경우 #f가 없는지 확인)
           (let ((valid-sources?
                  (if (list? srcs)
                      (every identity srcs)
                      srcs)))
             (when valid-sources?
               (set! executed-mors (cons m executed-mors))
               (let* ((vals (if (list? srcs)
                                (map core:cell-value srcs)
                                (list (core:cell-value srcs))))
                      (result ((cat:arrow-fn m) vals srcs))
                      (prop-val (car result))
                      (prop-effects (cdr result)))
                 (when (not (null? prop-effects))
                   (set! effects (append prop-effects effects)))
                 (when (not (eq? prop-val core:*nothing*))
                   (if (list? tgts)
                       (if (and (list? prop-val) (= (length prop-val) (length tgts)))
                           (for-each
                            (lambda (tgt v)
                              (when (and tgt (not (eq? v core:*nothing*)))
                                (let ((current (hash-ref potential-updates tgt '())))
                                  (hash-set! potential-updates tgt (cons v current)))))
                            tgts prop-val)
                           (error "Propagator output list length does not match targets" m))
                       (when tgts
                         (let ((current (hash-ref potential-updates tgts '())))
                           (hash-set! potential-updates tgts (cons prop-val current)))))))))))
       sorted-mors))
    (values potential-updates effects (reverse executed-mors))))

(define (_runtime-apply-updates potential-updates)
  (let ((changed? #f)
        (effects '())
        (changed-cells '())
        (updates (hash-map->list cons potential-updates)))
    (for-each
     (lambda (update)
       (let* ((cell (car update))
              (values (cdr update))
              (merge-fn (core:cell-merge-fn cell))
              (resolved-result (merge-fn cell values))
              (resolved-val (car resolved-result))
              (merge-effects (cdr resolved-result)))
         (set! effects (append merge-effects effects))
         (when (not (equal? (core:cell-value cell) resolved-val))
           (core:cell-set-value! cell resolved-val)
           (set! changed-cells (cons cell changed-cells))
           (set! changed? #t))))
     updates)
    (values changed? effects changed-cells)))

(define (runtime-step! system-or-net active-cells)
  (let* ((system (if (system? system-or-net) system-or-net (core:cell-system (car (cat:category-objects system-or-net)))))
         (C (get-net system)))
    (let-values (((potential-updates propagator-effects executed-mors)
                  (_runtime-collect-updates C active-cells)))
      (let-values (((changed-by-merge? merge-effects changed-cells)
                    (_runtime-apply-updates potential-updates)))
        (let* ((effects-this-pass (append propagator-effects merge-effects)))
          (let-values (((changed-by-plain-effects? activated-by-effects) (runtime-execute-effects effects-this-pass system)))
            (values (or changed-by-merge? changed-by-plain-effects?)
                    executed-mors
                    (delete-duplicates (append changed-cells activated-by-effects)))))))))

(define (runtime-settle! system-or-net)
  ;; First step is a full evaluation to find initial changes.
  (let-values (((changed? initial-trace changed-cells) (runtime-step! system-or-net #f)))
    ;; Now loop, propagating changes until a fixed point is reached.
    (let loop ((changed? changed?)
               (full-trace initial-trace)
               (active-cells changed-cells))
      (if changed?
          (let-values (((step-changed? step-trace step-changed-cells)
                        (runtime-step! system-or-net active-cells)))
            (loop step-changed?
                  (append full-trace step-trace)
                  step-changed-cells))
          (reverse full-trace)))))
