(define-module (cpnet runtime)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-11)
  #:use-module (ice-9 hash-table)
  #:use-module ((cpnet core) :prefix core:)
  #:use-module ((cpnet category) :prefix cat:)
  #:use-module (cpnet system)
  #:export (
	    runtime-settle!
	    runtime-step!
	    runtime-execute-effects
	    runtime-show-state))

(define (get-net system-or-net)
  (if (system? system-or-net)
      (system-get-net system-or-net)
      system-or-net))

(define (runtime-execute-effects effects)
  (let ((changed? #f))
    (for-each
     (lambda (effect)
       (case (core:effect-type effect)
         ((display) (display (core:effect-payload effect)))
         ((set-value)
          (let* ((payload (core:effect-payload effect))
                 (cell (car payload))
                 (new-val (cdr payload)))
            (when (not (equal? (core:cell-value cell) new-val))
              (core:cell-set-value! cell new-val)
              (set! changed? #t))))
         (else (format #t "Unknown effect: ~a\n" (core:effect-type effect)))))
     effects)
    changed?))

(define (runtime-show-state system-or-net title)
  (display (format #f "\n--- [~a] cpnet state ---\n" title))
  (let ((C (get-net system-or-net)))
    (for-each
     (lambda (c)
       (display (format #f "Cell ~a: ~a\n"
                        (core:cell-id c)
                        (core:cell-value c))))
     (sort (cat:category-objects C)
           (lambda (a b)
             (string<?
              (symbol->string (core:cell-id a))
              (symbol->string (core:cell-id b)))))))
  (display "--------------------------------\n"))

(define (_runtime-collect-updates C)
  (let ((effects '())
        (potential-updates (make-hash-table)))
    (for-each
     (lambda (m)
       (let* ((srcs (cat:arrow-dom m))
              (tgts (cat:arrow-cod m)))
         (let* ((vals (if (list? srcs)
                          (map core:cell-value srcs)
                          (core:cell-value srcs)))
                (result ((cat:arrow-fn m) vals srcs))
                (prop-val (car result))
                (prop-effects (cdr result)))
           (when (not (null? prop-effects))
             (set! effects (append prop-effects effects)))
           (when (not (eq? prop-val core:*nothing*))
             (if (list? tgts)
                 (if (and (list? prop-val) (= (length prop-val) (length tgts)))
                     (for-each
                      (lambda (tgt v)
                        (when (and tgt (not (eq? v core:*nothing*)))
                          (let ((current (hash-ref potential-updates tgt '())))
                            (hash-set! potential-updates tgt (cons v current)))))
                      tgts prop-val)
                     (error "Propagator output list length does not match targets" m))
                 (when tgts
                   (let ((current (hash-ref potential-updates tgts '())))
                     (hash-set! potential-updates tgts (cons prop-val current)))))))))
     (cat:category-morphisms C))
    (values potential-updates effects)))

(define (_runtime-apply-updates potential-updates)
  (let ((changed? #f)
        (effects '()))
    (hash-for-each
     (lambda (cell values)
       (let* ((merge-fn (core:cell-merge-fn cell))
              (resolved-result (merge-fn cell values))
              (resolved-val (car resolved-result))
              (merge-effects (cdr resolved-result)))
         (set! effects (append merge-effects effects))
         (when (not (equal? (core:cell-value cell) resolved-val))
           (core:cell-set-value! cell resolved-val)
           (set! changed? #t))))
     potential-updates)
    (values changed? effects)))

(define (runtime-step! system-or-net)
  (let ((C (get-net system-or-net)))
    (let-values (((potential-updates propagator-effects)
                  (_runtime-collect-updates C)))
      (let-values (((changed-by-merge? merge-effects)
                    (_runtime-apply-updates potential-updates)))
        (values (append propagator-effects merge-effects))))))



(define (runtime-settle! system-or-net)
  (let ((C (get-net system-or-net)))
    (let loop ((made-change? #t) (all-effects '()))
      (if (not made-change?)
          (reverse all-effects)
          (let-values (((potential-updates propagator-effects) (_runtime-collect-updates C)))
            (let-values (((changed-by-merge? merge-effects) (_runtime-apply-updates potential-updates)))
              (let* ((effects-this-pass (append propagator-effects merge-effects))
                     (changed-by-plain-effects? (runtime-execute-effects effects-this-pass)))
                (loop (or changed-by-merge? changed-by-plain-effects?)
                      (append effects-this-pass all-effects)))))))))
