(define-module (cpnet runtime)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-11)
  #:use-module ((cpnet core) :prefix core:)
  #:use-module ((cpnet category) :prefix cat:)
  #:export (
	    runtime-settle!
	    runtime-step!
	    runtime-execute-effects
	    runtime-show-state))

(define (runtime-execute-effects effects)
  (let ((changed? #f))
    (for-each
     (lambda (effect)
       (case (core:effect-type effect)
         ((display) (display (core:effect-payload effect)))
         ((set-value)
          (let* ((payload (core:effect-payload effect))
                 (cell (car payload))
                 (new-val (cdr payload)))
            (when (not (equal? (core:cell-value cell) new-val))
              (core:cell-set-value! cell new-val)
              (set! changed? #t))))
         ((connect)
          #t)
         (else (format #t "Unknown effect: ~a\n" (core:effect-type effect)))))
     effects)
    changed?))

(define (runtime-show-state C title)
  (display (format #f "\n--- [~a] cpnet state ---\n" title))
  (for-each
   (lambda (c)
     (display (format #f "Cell ~a: ~a\n"
                      (core:cell-id c)
                      (core:cell-value c))))
   (sort (cat:category-objects C)
         (lambda (a b)
           (string<?
             (symbol->string (core:cell-id a))
             (symbol->string (core:cell-id b))))))
  (display "--------------------------------\n"))

(define (_runtime-step! C)
  (let ((changed-this-pass? #f)
        (effects-this-pass '())
        (potential-updates (make-hash-table)))
    (for-each
     (lambda (m)
       (let* ((src (cat:arrow-dom m))
              (tgt (cat:arrow-cod m))
              (src-val (core:cell-value src)))
         (when (not (eq? src-val #f))
           (let ((result ((cat:arrow-fn m) src-val src)))
             (when (not (null? (cdr result)))
               (set! effects-this-pass (append (cdr result) effects-this-pass)))
             (when (not (eq? (car result) #f))
               (let ((current (hash-ref potential-updates tgt '())))
                 (hash-set! potential-updates tgt (cons result current))))))))
     (cat:category-morphisms C))
    (hash-for-each
     (lambda (cell updates)
       (let* ((values (map car updates))
              (merge-fn (core:cell-merge-fn cell))
              (resolved-result (merge-fn cell values))
              (resolved-val (car resolved-result))
              (merge-effects (cdr resolved-result)))
         (set! effects-this-pass (append merge-effects effects-this-pass))
         (when (not (equal? (core:cell-value cell) resolved-val))
           (core:cell-set-value! cell resolved-val)
           (set! changed-this-pass? #t))))
     potential-updates)
    (cons changed-this-pass? effects-this-pass)))

(define (runtime-step! C)
  (let* ((result (_runtime-step! C))
         (effects (cdr result)))
    (reverse effects)))

(define (runtime-settle! C)
  (let loop ((made-change? #t) (all-effects '()))
    (if (not made-change?)
      (reverse all-effects)
      (let* ((step-result (_runtime-step! C))
             (changed-by-propagator? (car step-result))
             (effects-this-pass (cdr step-result)))
        (let-values (((network-changed? other-effects)
                      (let ((connect-effects (filter (lambda (e) (eq? (core:effect-type e) 'connect)) effects-this-pass))
                            (other-effects (filter (lambda (e) (not (eq? (core:effect-type e) 'connect))) effects-this-pass)))
                        (values
                         (let ((changed? #f))
                           (for-each
                            (lambda (effect)
                              (let* ((payload (core:effect-payload effect))
                                     (src (car payload))
                                     (tgt (cdr payload)))
                                (unless (eq? src tgt)
                                  (let ((p (core:make-propagator
                                            (string->symbol (format #f "dyn-conn-~a->~a" (core:cell-id src) (core:cell-id tgt)))
                                            src tgt
                                            (lambda (v _) (cons v '())))))
                                    (unless (cat:category-has-morphism? C p)
                                      (cat:category-add-morphism C p)
                                      (set! changed? #t))))))
                            connect-effects)
                           changed?)
                         other-effects))))
          (let ((changed-by-effect? (runtime-execute-effects other-effects)))
            (loop (or changed-by-propagator? changed-by-effect? network-changed?)
                  (append effects-this-pass all-effects))))))))
