(define-module (cpnet sexp-loader)
  #:use-module (srfi srfi-1)
  #:use-module (cpnet core)
  #:use-module (cpnet dsl)
  #:use-module (cpnet scenario)
  #:use-module (cpnet system)
  #:use-module (cpnet runtime)
  #:export (load-system-from-sexp
            load-system-from-file))

;; `apply-gate`에 사용될 빌더의 인자 및 결과 개수(arity)가 올바른지 정적으로 확인합니다.
(define (static-apply-arity-check builder arg-refs result-refs)
  (let* ((sig (builder-signature builder))
         (in-ports (cadr (assoc 'inputs sig)))
         (out-ports (cadr (assoc 'outputs sig))))
    (unless (and (= (length arg-refs) (length in-ports))
                 (= (length result-refs) (length out-ports)))
      (error 'sexp-loader-arity-mismatch
             (format #f "SEXP Loader: Arity mismatch for apply-gate with builder ~a. Expected ~a inputs and ~a outputs, but got ~a and ~a."
                     (builder-name builder)
                     (length in-ports)
                     (length out-ports)
                     (length arg-refs)
                     (length result-refs))))))

;; S-expression으로 표현된 값을 실제 Scheme 값으로 평가합니다. (예: `(quote foo)` -> `foo`)
(define (eval-value-sexp sexp)
  (if (and (list? sexp) (> (length sexp) 0))
      (case (car sexp)
        ((quote) (cadr sexp))
        ((builder) (get-builder (cadr sexp)))
        (else sexp))
      sexp))

;; S-expression으로부터 시스템 정의를 로드하고 시스템 객체를 생성합니다.
(define (load-system-from-sexp sexp)
  (unless (and (list? sexp) (eq? (car sexp) 'system))
    (error "SEXP Loader: Expected format `(system <name> ...)`" sexp))
  (let* ((sys-name (cadr sexp))
	 (sys (make-system sys-name))
	 (clauses (cddr sexp)))
    (parameterize ((current-system sys))
      (for-each
       (lambda (clause)
	 (let ((type (car clause)))
           (case type
             ((interface)
              (let* ((builder-name (cadr clause))
                     (builder (get-builder builder-name)))
		((builder-function builder))))
             ((subsystems)
              (for-each
               (lambda (sub-def)
		 (let* ((def (if (and (list? sub-def) (= 1 (length sub-def)) (list? (car sub-def)))
				 (car sub-def)
				 sub-def))
			(instance-name (car def))
			(builder-name (cadr def))
			(builder (get-builder builder-name)))
                   (add-subsystem! sys ((builder-function builder) instance-name))))
               (cdr clause)))
             ((apply)
              (let* ((apply-instance-name (cadr clause))
                     (apply-clauses (cddr clause))
                     (code-clause (find (lambda (c) (eq? (car c) 'code)) apply-clauses))
                     (args-clause (find (lambda (c) (eq? (car c) 'args)) apply-clauses))
                     (results-clause (find (lambda (c) (eq? (car c) 'results)) apply-clauses))
                     (builder-name (cadr code-clause))
                     (builder (get-builder builder-name))
                     (arg-refs (cdr args-clause))
                     (result-refs (cdr results-clause)))

		(static-apply-arity-check builder arg-refs result-refs)

		(let ((code-cell (get-cell apply-instance-name 'apply-interface 'code))
                      (args-cell (get-cell apply-instance-name 'apply-interface 'args))
                      (results-cell (get-cell apply-instance-name 'apply-interface 'results)))
                  (trigger code-cell builder)
                  (trigger args-cell (map (lambda (ref) (apply get-cell ref)) arg-refs))
                  (trigger results-cell (map (lambda (ref) (apply get-cell ref)) result-refs)))))
             ((connections wires)
              (for-each
               (lambda (wire-def)
		 (let* ((the-wire (car wire-def))
			(from-ref (car the-wire))
			(to-ref (caddr the-wire)))
                   (wire (apply get-cell from-ref) (apply get-cell to-ref))))
               (cdr clause)))
             ((triggers)
              (for-each
               (lambda (trigger-def)
                 (let* ((the-trigger (car trigger-def))
                        (cell-ref (car the-trigger))
                        (value-sexp (cadr the-trigger))
                        (cell (apply get-cell cell-ref))
                        (value (eval-value-sexp value-sexp)))
                   (trigger cell value)))
               (cdr clause)))
             (else
              (error "SEXP Loader: Unknown clause type" type)))))
       clauses))
    sys))

;; 파일 경로를 받아 해당 파일의 S-expression으로부터 시스템을 로드합니다.
(define (load-system-from-file file-path)
  (call-with-input-file file-path
    (lambda (port)
      (load-system-from-sexp (read port)))))
